### ISSUE TITLE
Doesn't work with KH1 steam

### ISSUE THREAD

**Issue by DairyProducts** [Dekirai/MultiPresence#2]
![image](https://github.com/Dekirai/MultiPresence/assets/66636627/24f2f485-d77a-42da-a445-800c425b1636)
Despite not being on beginner or level 1 or at the station of awakening, the RP card says I am and doesn't update when going to another world.

**Comment by Dekirai** [comment]
Fixed with https://github.com/Dekirai/MultiPresence/commit/3bf8c905c5375dec3e902c0ba80e5a69621d5514
